### ISSUE TITLE
Spurious dot in onCreated callback

### ISSUE THREAD

**Issue by diegonc** [qnipp/meteor-treeview#2]
There's an extra dot in the following line (client/tree_view.js:29).

``` javascript
} else if(! data.Context || ! dataContext.core || ! dataContext.core.data) {
//--------------^
```

**Comment by fknipp** [comment]
Thanks for this comment, I've fixed it in https://github.com/qnipp/meteor-treeview/commit/b8704c5fe80f1a31c017e58b36f9407ed73b13e9
