### ISSUE TITLE
selectAll

### ISSUE THREAD

**Issue by luixal** [qnipp/meteor-treeview#3]
Hi,

Having the `openAll` field is great, and I feel like having `selectAll` would be great too, at least for **consistency**.

I know you can get the same effect using the mapping field like this:

``` javascript
mapping: {
  state: {
    selected: true,
    opened: true
  }
}
```

But it feels suitable to be another field like `openAll`. What do you think?

:)

**Comment by fknipp** [comment]
Thanks for this comment, *selectAll* has been added, see the demo on http://treeview.meteor.qnipp.com/

**Comment by luixal** [comment]
Great!
Thanks :)
