### ISSUE TITLE
DB structure

### ISSUE THREAD

**Issue by valorloff** [qnipp/meteor-treeview#4]
Hi!
is it correct database structure for your TreeView?:
```
Schemas.Categories = new SimpleSchema({
img: {type: String},
name: { type: String},
description: {type: String},
parent: {type: String	},
categoriesId: {type: Number}
});
```
Is it just parentId enough?

**Comment by fknipp** [comment]
Hello!

Yes, the **parent** field containing the **_id** of the parent is just enough to form the tree.

If you want to set the icon used in the tree, you must use the **icon** field (not **img**), the **name** field should be named **text**.

Maybe, I should improve the documentation ;)

**Comment by valorloff** [comment]
Thank for quick response!
And what about if i write: 
```
"mapping": {
      "text" : "name",
      "icon" : "img"
```
then i can remain "name","img" fields in Categories?
I don't want to spoil the DB because tree..

**Comment by fknipp** [comment]
Yes, this is absolutely correct.
