### ISSUE TITLE
jstree manipulations

### ISSUE THREAD

**Issue by valorloff** [qnipp/meteor-treeview#5]
I want some manipulations with jstree nodes:
```
  events: {
          changed: function(e, item, data) {
          data.instance.toggle_node(data.node);
```
but console.log(data) says:
```
Object
parent: undefined
position: undefined
text: undefined
```
what is wrong?

**Comment by fknipp** [comment]
For *changed* events only the *item* parameter can be used, it contains all selected item ids as array. 

The *data* parameter is set only for the events to create, move, copy and delete nodes. It contains only _text_, _position_ and _parent_. The [list of events of the underlying jsTree](https://www.jstree.com/api/#/?q=.jstree%20Event) shows, which events provide these fields.
